apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sam-test-comp-1
spec:
  type: service
  owner: sblausten
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sam-test-api-1
spec:
  type: openapi
  owner: sblausten
  lifecycle: experimental
  definition: |
    abc
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sam-test-comp-2
spec:
  type: service
  owner: sblausten
  lifecycle: experimental
  providesApis:
    - sam-test-api-1
  parentOf:
    - api:default/sam-test-api-1
  parent:
    - component:default/sam-test-comp-1
---
