apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: annotation-fragment-with-pr
  title: Add PagerDuty Service Annotation with PR
  description: Adds a PagerDuty service-id annotation to an existing entity with fragment and optional pr
  tags:
    - pagerduty
spec:
  owner: platform-team
  type: annotation

  parameters:
    - title: Entity Selection
      required:
        - entity
      properties:
        entity:
          title: Select Entity
          type: string
          description: Choose the entity to add the PagerDuty annotation to
          ui:field: EntityPicker
          ui:options:
            allowKinds:
              - Component
              - API
              - Resource

    - title: PagerDuty Configuration
      required:
        - pagerduty_service
      properties:
        pagerduty_service:
          title: PagerDuty Service
          type: string
          description: Select the PagerDuty service to associate with this entity
          ui:field: SelectFieldFromApi
          ui:options:
            path: proxy/pagerduty/services
            arraySelector: services
            valueSelector: id
            labelTemplate: '{{ item.name }} ({{ item.summary }})'

    - title: Update Options
      properties:
        create_pr:
          title: Create Pull Request
          type: boolean
          description: Create a pull request to update the catalog-info.yaml file in the repository (only works for GitHub-hosted entities)
          default: false
        pr_title:
          title: Pull Request Title
          type: string
          description: Title for the pull request
          default: 'Add PagerDuty service annotation'
          ui:options:
            showIfValue:
              create_pr: true
        pr_description:
          title: Pull Request Description
          type: string
          description: Description for the pull request
          default: 'This PR adds the PagerDuty service annotation to the catalog-info.yaml file'
          ui:widget: textarea
          ui:options:
            showIfValue:
              create_pr: true

  steps:
    - id: parse-entity-ref
      name: Parse Entity Reference
      action: debug:log
      input:
        message: 'Adding PagerDuty service ${{ parameters.pagerduty_service }} to entity ${{ parameters.entity }}'

    - id: create-catalog-fragment
      name: Create Catalog Fragment with PagerDuty Annotation
      action: http:backstage:request
      input:
        method: POST
        path: catalog/fragments
        headers:
          'content-type': 'application/json'
        body:
          decorator:
            entityRef: ${{ parameters.entity }}
            fragment:
              metadata:
                annotations:
                  pagerduty.com/service-id: ${{ parameters.pagerduty_service }}
              spec:
            source: 'scaffolder'

    # Conditional steps for creating PR
    - id: fetch-entity-details
      name: Fetch Entity Details
      action: catalog:fetch
      if: ${{ parameters.create_pr }}
      input:
        entityRef: ${{ parameters.entity }}

    - id: check-github-source
      name: Check if Entity is GitHub-hosted
      action: debug:log
      if: ${{ parameters.create_pr }}
      input:
        message: 'Entity source location: ${{ steps["fetch-entity-details"].output.entity.metadata.annotations["backstage.io/source-location"] }}'

    - id: fetch-catalog-file
      name: Fetch catalog-info.yaml
      action: fetch:plain:file
      if: ${{ parameters.create_pr and steps["fetch-entity-details"].output.entity.metadata.annotations["backstage.io/source-location"] }}
      input:
        url: ${{ steps["fetch-entity-details"].output.entity.metadata.annotations["backstage.io/source-location"] | replace("/blob/", "/") | replace("/tree/", "/") }}/catalog-info.yaml
        targetPath: ./

    - id: parse-catalog-file
      name: Parse catalog-info.yaml
      action: roadiehq:utils:fs:parse
      if: ${{ parameters.create_pr and steps["fetch-entity-details"].output.entity.metadata.annotations["backstage.io/source-location"] }}
      input:
        path: ./catalog-info.yaml
        parser: yaml

    - id: merge-annotation
      name: Add PagerDuty Annotation to Catalog File
      action: roadiehq:utils:merge
      if: ${{ parameters.create_pr and steps["fetch-entity-details"].output.entity.metadata.annotations["backstage.io/source-location"] }}
      input:
        path: ./catalog-info.yaml
        content:
          metadata:
            annotations:
              pagerduty.com/service-id: ${{ parameters.pagerduty_service }}

    - id: create-pull-request
      name: Create Pull Request
      action: publish:github:pull-request
      if: ${{ parameters.create_pr and steps["fetch-entity-details"].output.entity.metadata.annotations["backstage.io/source-location"] }}
      input:
        repoUrl: ${{ steps["fetch-entity-details"].output.entity.metadata.annotations["backstage.io/source-location"] | replace("https://github.com/", "") | replace("/blob/main", "") | replace("/blob/master", "") | replace("/tree/main", "") | replace("/tree/master", "") | replace("/catalog-info.yaml", "") }}
        branchName: add-pagerduty-annotation-${{ parameters.pagerduty_service }}
        title: ${{ parameters.pr_title }}
        description: |
          ${{ parameters.pr_description }}
          
          **Changes:**
          - Added `pagerduty.com/service-id: ${{ parameters.pagerduty_service }}` annotation to catalog-info.yaml
          
          **Entity:** ${{ parameters.entity }}
          **PagerDuty Service ID:** ${{ parameters.pagerduty_service }}
        commitMessage: 'Add PagerDuty service annotation: ${{ parameters.pagerduty_service }}'
        sourcePath: ./

  output:
    links:
      - title: View Entity in Catalog
        url: ${{ steps['create-catalog-fragment'].output.body.fragment.metadata.annotations['backstage.io/view-url'] or '/catalog/' + parameters.entity }}
      - title: PagerDuty Service Dashboard
        url: 'https://your-org.pagerduty.com/services/${{ parameters.pagerduty_service }}'
      - title: GitHub Pull Request
        url: ${{ steps['create-pull-request'].output.remoteUrl }}
        condition: ${{ parameters.create_pr and steps["create-pull-request"] }}